# Generated by Django 2.2.19 on 2022-08-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220823_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriplion',
            new_name='description',
        ),
    ]
