# Generated by Django 2.2.9 on 2022-09-13 19:23

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220829_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
